import ReportNav from '@/components/report/ReportNav'
import styles from './page.module.css'

export default function TermsPage() {
  return (
    <div className={styles.bg}>
      <ReportNav />
      <main className={styles.page}>

        <header className={styles.hero}>
          <p className={styles.eyebrow}>Legal</p>
          <h1 className={styles.h1}>Terms of Service</h1>
          <p className={styles.meta}>Effective January 1, 2026 · Last updated March 2026</p>
        </header>

        <div className={styles.body}>

          <section className={styles.section}>
            <h2 className={styles.h2}>1. Acceptance of Terms</h2>
            <p>By accessing or using Thesis (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.h2}>2. Description of Service</h2>
            <p>Thesis is an AI-powered equity research platform that generates investment research reports using live market data and artificial intelligence. Reports are produced by the Thesis Intelligence Engine (TIE), powered by Claude claude-sonnet-4-20250514 (Anthropic) and financial data from Financial Modeling Prep.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.h2}>3. Not Investment Advice</h2>
            <p>All content generated by Thesis is for <strong>informational and educational purposes only</strong> and does not constitute investment advice, financial advice, trading advice, or any other type of advice. Nothing on this Service should be construed as a recommendation to buy, sell, or hold any security.</p>
            <p>You should independently verify all information before making any investment decision. Past performance is not indicative of future results. Investing involves risk, including the possible loss of principal.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.h2}>4. Accuracy of Information</h2>
            <p>While we strive to provide accurate and up-to-date information, Thesis makes no representations or warranties of any kind regarding the completeness, accuracy, reliability, or suitability of any information generated by the Service. Market data is sourced from third-party providers and may be delayed or contain errors.</p>
            <p>AI-generated analysis reflects the model&apos;s interpretation of available data and should not be treated as authoritative or exhaustive. Always consult a qualified financial professional before making investment decisions.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.h2}>5. Acceptable Use</h2>
            <p>You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to:</p>
            <ul>
              <li>Use the Service for any unlawful purpose or in violation of any regulations</li>
              <li>Attempt to gain unauthorized access to any part of the Service</li>
              <li>Reproduce, distribute, or resell reports without permission</li>
              <li>Use automated means to scrape or extract data from the Service at scale</li>
              <li>Misrepresent AI-generated content as independent research</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2 className={styles.h2}>6. Intellectual Property</h2>
            <p>The Service and its original content, features, and functionality are owned by Thesis and are protected by applicable intellectual property laws. AI-generated reports are provided for personal, non-commercial use only.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.h2}>7. Third-Party Services</h2>
            <p>The Service relies on third-party APIs including Financial Modeling Prep for market data and Anthropic&apos;s Claude API for AI analysis. Thesis is not responsible for the availability, accuracy, or terms of these third-party services.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.h2}>8. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, Thesis shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation loss of profits, data, or goodwill, arising out of or in connection with your use of the Service.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.h2}>9. Changes to Terms</h2>
            <p>We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting. Your continued use of the Service following any changes constitutes your acceptance of the revised Terms.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.h2}>10. Contact</h2>
            <p>If you have any questions about these Terms, please reach out through the Thesis platform.</p>
          </section>

        </div>
      </main>
    </div>
  )
}
