import { NextRequest, NextResponse } from 'next/server'
import {
  getStockSnapshot,
  formatMarketCap,
  formatPct,
  formatMultiple,
  type StockSnapshot,
} from '@/lib/fmp'
import type { TIEReport, KeyMetric } from '@/lib/types'

/**
 * GET /api/report/[ticker]
 *
 * Session 2: Fetches live data from Financial Modeling Prep and returns a
 * TIEReport populated with real market data. Narrative sections and full
 * DCF modeling are placeholder text — wired in Session 3.
 */

function buildMetrics(snap: StockSnapshot): KeyMetric[] {
  const sign = snap.changePct >= 0 ? '+' : ''
  return [
    {
      label: 'Price',
      value: `$${snap.price.toFixed(2)}`,
      sub: `${sign}${snap.changePct.toFixed(2)}% today`,
    },
    { label: 'Market Cap', value: formatMarketCap(snap.marketCap) },
    { label: 'P/E (TTM)', value: snap.pe ? `${snap.pe.toFixed(1)}x` : 'N/A' },
    { label: 'EV / Revenue', value: formatMultiple(snap.evToRevenue) },
    { label: 'Rev. Growth', value: formatPct(snap.revenueGrowth) },
    { label: 'Gross Margin', value: formatPct(snap.grossMargin) },
  ]
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ ticker: string }> }
) {
  const { ticker } = await params
  const symbol = ticker.toUpperCase()

  if (!/^[A-Z]{1,5}$/.test(symbol)) {
    return NextResponse.json(
      { error: `Invalid ticker symbol: ${symbol}` },
      { status: 400 }
    )
  }

  try {
    const snap = await getStockSnapshot(symbol)

    const report: TIEReport = {
      // Identity
      ticker: snap.ticker,
      exchange: snap.exchange,
      companyName: snap.name,
      sector: snap.sector,
      reportType: 'Market Data Snapshot',
      generatedAt: new Date().toISOString(),

      // Verdict — placeholder until TIE Engine generates full analysis (Session 3)
      rating: 'HOLD',
      priceTarget: {
        base: Math.round(snap.price * 1.10),
        bull: Math.round(snap.price * 1.25),
        bear: Math.round(snap.price * 0.85),
        currency: snap.currency,
      },
      currentPrice: snap.price,

      // Real live metrics from FMP
      metrics: buildMetrics(snap),

      // Narrative — placeholders for Session 3 AI generation
      investmentThesis: {
        title: 'Investment Thesis',
        content: `Full TIE analysis for ${snap.name} (${snap.ticker}) is pending.\n\nThe TIE Engine will generate a comprehensive investment thesis — covering competitive positioning, growth catalysts, and valuation framework — in Session 3.`,
      },
      businessOverview: {
        title: 'Business Overview',
        content: snap.description
          ? snap.description
          : `${snap.name} operates in the ${snap.sector} sector (${snap.industry}).`,
      },
      financialAnalysis: {
        title: 'Financial Analysis',
        content: `Live financial metrics for ${snap.ticker} are shown above.\n\nDetailed financial modeling, margin trajectory analysis, and earnings quality assessment will be generated by the TIE Engine in Session 3.`,
      },
      riskFactors: {
        title: 'Risk Factors',
        content: `Comprehensive risk analysis for ${snap.ticker} — covering competitive, regulatory, and macroeconomic risks — will be generated by the TIE Engine in Session 3.`,
      },

      // DCF — placeholder inputs, no projections until Session 3
      dcf: {
        intrinsicValue: snap.price,
        impliedUpside: 0,
        inputs: {
          wacc: 0.095,
          terminalGrowthRate: 0.03,
          projectionYears: 5,
          revenueCAGR: 0.15,
        },
        yearlyProjections: [],
      },

      // Scenarios — placeholder until Session 3
      scenarios: [
        {
          label: 'Bull Case',
          target: Math.round(snap.price * 1.25),
          upside: 25,
          description: 'Full scenario modeling will be generated by TIE Engine in Session 3.',
          keyAssumptions: ['TIE analysis pending — Session 3'],
        },
        {
          label: 'Base Case',
          target: Math.round(snap.price * 1.10),
          upside: 10,
          description: 'Full scenario modeling will be generated by TIE Engine in Session 3.',
          keyAssumptions: ['TIE analysis pending — Session 3'],
        },
        {
          label: 'Bear Case',
          target: Math.round(snap.price * 0.85),
          upside: -15,
          description: 'Full scenario modeling will be generated by TIE Engine in Session 3.',
          keyAssumptions: ['TIE analysis pending — Session 3'],
        },
      ],

      // Comparables — subject company only until Session 3 builds peer set
      comparables: [
        {
          ticker: snap.ticker,
          name: snap.name,
          price: `$${snap.price.toFixed(2)}`,
          marketCap: formatMarketCap(snap.marketCap),
          peForward: snap.pe ? `${snap.pe.toFixed(1)}x` : 'N/A',
          evRevenue: formatMultiple(snap.evToRevenue),
          revenueGrowth: formatPct(snap.revenueGrowth),
          grossMargin: formatPct(snap.grossMargin),
          rating: 'HOLD',
        },
      ],
    }

    return NextResponse.json(report)
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error'
    console.error(`[report/${symbol}]`, message)
    return NextResponse.json(
      { error: `Failed to fetch data for ${symbol}: ${message}` },
      { status: 500 }
    )
  }
}
